// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/orderProcessing.proto

package processingProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderProcessingService_AddOrder_FullMethodName    = "/orderProcessing.orderProcessingService/AddOrder"
	OrderProcessingService_CheckStatus_FullMethodName = "/orderProcessing.orderProcessingService/CheckStatus"
)

// OrderProcessingServiceClient is the client API for OrderProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderProcessingServiceClient interface {
	AddOrder(ctx context.Context, in *OrderInfo, opts ...grpc.CallOption) (*OrderStatus, error)
	CheckStatus(ctx context.Context, in *OrderInfo, opts ...grpc.CallOption) (*OrderStatus, error)
}

type orderProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderProcessingServiceClient(cc grpc.ClientConnInterface) OrderProcessingServiceClient {
	return &orderProcessingServiceClient{cc}
}

func (c *orderProcessingServiceClient) AddOrder(ctx context.Context, in *OrderInfo, opts ...grpc.CallOption) (*OrderStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatus)
	err := c.cc.Invoke(ctx, OrderProcessingService_AddOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderProcessingServiceClient) CheckStatus(ctx context.Context, in *OrderInfo, opts ...grpc.CallOption) (*OrderStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderStatus)
	err := c.cc.Invoke(ctx, OrderProcessingService_CheckStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderProcessingServiceServer is the server API for OrderProcessingService service.
// All implementations must embed UnimplementedOrderProcessingServiceServer
// for forward compatibility.
type OrderProcessingServiceServer interface {
	AddOrder(context.Context, *OrderInfo) (*OrderStatus, error)
	CheckStatus(context.Context, *OrderInfo) (*OrderStatus, error)
	mustEmbedUnimplementedOrderProcessingServiceServer()
}

// UnimplementedOrderProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderProcessingServiceServer struct{}

func (UnimplementedOrderProcessingServiceServer) AddOrder(context.Context, *OrderInfo) (*OrderStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrder not implemented")
}
func (UnimplementedOrderProcessingServiceServer) CheckStatus(context.Context, *OrderInfo) (*OrderStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStatus not implemented")
}
func (UnimplementedOrderProcessingServiceServer) mustEmbedUnimplementedOrderProcessingServiceServer() {
}
func (UnimplementedOrderProcessingServiceServer) testEmbeddedByValue() {}

// UnsafeOrderProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderProcessingServiceServer will
// result in compilation errors.
type UnsafeOrderProcessingServiceServer interface {
	mustEmbedUnimplementedOrderProcessingServiceServer()
}

func RegisterOrderProcessingServiceServer(s grpc.ServiceRegistrar, srv OrderProcessingServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderProcessingService_ServiceDesc, srv)
}

func _OrderProcessingService_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderProcessingServiceServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderProcessingService_AddOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderProcessingServiceServer).AddOrder(ctx, req.(*OrderInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderProcessingService_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderProcessingServiceServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderProcessingService_CheckStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderProcessingServiceServer).CheckStatus(ctx, req.(*OrderInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderProcessingService_ServiceDesc is the grpc.ServiceDesc for OrderProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderProcessing.orderProcessingService",
	HandlerType: (*OrderProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrder",
			Handler:    _OrderProcessingService_AddOrder_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _OrderProcessingService_CheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orderProcessing.proto",
}
